/**
 * Render the Supabase Auth email templates to static HTML files that you paste
 * into the Supabase dashboard (Authentication → Emails → Templates).
 *
 *   npm run email:auth
 *
 * Output: src/emails/auth-dist/*.html + README.md
 *
 * Supabase uses Go-template variables ({{ .ConfirmationURL }}, {{ .Token }},
 * {{ .NewEmail }}, …). They pass through React Email rendering verbatim, so the
 * produced HTML is paste-ready.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { renderEmailHtml } from '../render'
import ConfirmSignup from '../templates/auth/ConfirmSignup'
import MagicLink from '../templates/auth/MagicLink'
import Invite from '../templates/auth/Invite'
import ResetPassword from '../templates/auth/ResetPassword'
import EmailChange from '../templates/auth/EmailChange'

const OUT = join(__dirname, '..', 'auth-dist')

const TEMPLATES = [
  { file: 'confirm-signup.html',  dashboard: 'Confirm signup',         Component: ConfirmSignup },
  { file: 'invite.html',          dashboard: 'Invite user',            Component: Invite },
  { file: 'magic-link.html',      dashboard: 'Magic Link',             Component: MagicLink },
  { file: 'reset-password.html',  dashboard: 'Reset Password',         Component: ResetPassword },
  { file: 'change-email.html',    dashboard: 'Change Email Address',   Component: EmailChange },
] as const

async function main() {
  mkdirSync(OUT, { recursive: true })

  for (const t of TEMPLATES) {
    const html = await renderEmailHtml(t.Component as any, {})
    // Sanity: the action URL var must have survived rendering.
    if (!html.includes('{{ .ConfirmationURL }}')) {
      throw new Error(`${t.file}: {{ .ConfirmationURL }} did not survive rendering — check the template`)
    }
    writeFileSync(join(OUT, t.file), html, 'utf8')
    console.log(`✓ ${t.file}  (paste into Supabase template: "${t.dashboard}")`)
  }

  const readme = `# Supabase Auth email templates (Frequency-branded)

Generated by \`npm run email:auth\` from \`src/emails/templates/auth/*.tsx\`.
**Do not hand-edit these .html files** — edit the .tsx source and re-run.

These cannot be rendered live by our backend (Supabase sends auth mail itself),
so paste each file's contents into the Supabase dashboard:

**Authentication → Emails → Templates** → pick the template → switch the body to
HTML source → paste the matching file → Save.

| File | Supabase template | Notes |
|------|-------------------|-------|
${TEMPLATES.map(t => `| \`${t.file}\` | **${t.dashboard}** | |`).join('\n')}

Supabase variables used (substituted by Supabase at send time):
\`{{ .ConfirmationURL }}\`, \`{{ .Token }}\`, \`{{ .NewEmail }}\`.

The **Invite user** template also powers in-app team invites
(\`routes/teams.ts\` → \`inviteUserByEmail\`).

Subjects (set in the dashboard, above the body):
- Confirm signup → \`Confirm your email · Frequency\`
- Invite user → \`You've been invited to Frequency\`
- Magic Link → \`Your Frequency sign-in link\`
- Reset Password → \`Reset your Frequency password\`
- Change Email Address → \`Confirm your new email · Frequency\`
`
  writeFileSync(join(OUT, 'README.md'), readme, 'utf8')
  console.log(`\nWrote ${TEMPLATES.length} templates + README.md to src/emails/auth-dist/`)
}

main().catch((e) => { console.error(e); process.exit(1) })
