-- Workflow skills: reusable workflow templates that can be matched to user descriptions
create table if not exists public.workflow_skills (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid references auth.users(id) on delete cascade,  -- null = platform global skill
  name          text not null,
  description   text not null,   -- plain English description for matching
  tags          text[] default '{}',
  workflow_json jsonb not null,   -- full ParsedWorkflow JSON
  usage_count   integer default 0,
  is_global     boolean default false,
  created_at    timestamptz default now()
);

alter table public.workflow_skills enable row level security;

create policy "Users see own and global skills" on public.workflow_skills
  for select using (auth.uid() = user_id or is_global = true);

create policy "Users manage own skills" on public.workflow_skills
  for all using (auth.uid() = user_id);

-- Seed 5 global skills (null user_id, is_global = true)
insert into public.workflow_skills (user_id, name, description, tags, is_global, workflow_json) values
(null, 'Lead Welcome', 'When a new lead messages us on WhatsApp, send them a welcome message with our product brochure and a quick reply to book a demo', ARRAY['lead', 'welcome', 'onboarding'], true, '{"workflow_name":"Lead Welcome Flow","description":"Automatically welcome new WhatsApp leads","trigger_summary":"Any new inbound WhatsApp message","nodes":[{"id":"n1","type":"trigger_inbound_any","label":"New WhatsApp message","description":"Fires when any new contact messages","missing_config":[],"warnings":[],"compliance_note":null,"template_required":false},{"id":"n2","type":"send_template","label":"Send welcome template","description":"Send branded welcome message with PDF attachment","missing_config":[{"field":"template_name","label":"Template name","type":"text","placeholder":"lead_welcome","required":true}],"warnings":[],"compliance_note":"Template must be approved by Meta before use","template_required":true},{"id":"n3","type":"collect_input","label":"Collect interest","description":"Ask if they want to book a demo","missing_config":[{"field":"prompt","label":"Question to ask","type":"textarea","placeholder":"Would you like to book a free demo?","required":true}],"warnings":[],"compliance_note":null,"template_required":false},{"id":"n4","type":"end_flow","label":"End","description":"Flow ends","missing_config":[],"warnings":[],"compliance_note":null,"template_required":false}],"required_integrations":[],"templates_needed":[{"suggested_name":"lead_welcome","category":"MARKETING","purpose":"Welcome new leads","body_preview":"Hi {{1}}, welcome to our service! Here is our product brochure. Would you like to book a free demo?","approval_time":"24-48 hours"}],"compliance_flags":[],"missing_info":[],"blocking_issues":[],"overall_status":"needs_templates","config_completion_percent":60}'),

(null, 'Payment Confirmation', 'After a customer pays on Razorpay, immediately send them a WhatsApp payment confirmation and receipt', ARRAY['payment', 'razorpay', 'confirmation', 'receipt'], true, '{"workflow_name":"Payment Confirmation","description":"Send WhatsApp confirmation after Razorpay payment","trigger_summary":"Razorpay payment webhook","nodes":[{"id":"n1","type":"trigger_webhook","label":"Razorpay payment webhook","description":"Receives payment.captured events from Razorpay","missing_config":[{"field":"webhook_url","label":"Webhook URL (configure in Razorpay dashboard)","type":"url","placeholder":"https://your-server.com/webhook/razorpay","required":true}],"warnings":["Configure this URL in your Razorpay dashboard under Webhooks"],"compliance_note":null,"template_required":false},{"id":"n2","type":"send_template","label":"Send payment confirmation","description":"Send payment receipt via WhatsApp template","missing_config":[{"field":"template_name","label":"Approved template name","type":"text","placeholder":"payment_confirmation","required":true}],"warnings":[],"compliance_note":"UTILITY category templates have higher deliverability","template_required":true},{"id":"n3","type":"end_flow","label":"End","description":"Flow ends","missing_config":[],"warnings":[],"compliance_note":null,"template_required":false}],"required_integrations":[{"key":"razorpay","name":"Razorpay","reason":"To receive payment webhook events"}],"templates_needed":[{"suggested_name":"payment_confirmation","category":"UTILITY","purpose":"Payment receipt","body_preview":"Hi {{1}}, your payment of ₹{{2}} for {{3}} has been received. Transaction ID: {{4}}. Thank you!","approval_time":"24-48 hours"}],"compliance_flags":[],"missing_info":[],"blocking_issues":[],"overall_status":"needs_config","config_completion_percent":40}'),

(null, 'Review Request', 'After order delivery, ask customers for a Google review or product rating using quick reply buttons', ARRAY['review', 'rating', 'feedback', 'post-purchase'], true, '{"workflow_name":"Review Request","description":"Ask for review after purchase or delivery","trigger_summary":"Scheduled 3 days after purchase","nodes":[{"id":"n1","type":"trigger_scheduled","label":"Scheduled trigger","description":"Runs 3 days after order delivered","missing_config":[{"field":"delay_days","label":"Days after purchase","type":"number","placeholder":"3","required":true}],"warnings":[],"compliance_note":null,"template_required":false},{"id":"n2","type":"send_template","label":"Send review request","description":"Ask for review with quick reply buttons","missing_config":[{"field":"template_name","label":"Template name","type":"text","placeholder":"review_request","required":true}],"warnings":[],"compliance_note":"Use MARKETING category for review requests","template_required":true},{"id":"n3","type":"collect_input","label":"Collect rating","description":"Wait for their rating response","missing_config":[],"warnings":[],"compliance_note":null,"template_required":false},{"id":"n4","type":"update_sheet","label":"Log to Google Sheet","description":"Save rating to your tracking spreadsheet","missing_config":[{"field":"spreadsheet_id","label":"Google Sheet ID","type":"text","placeholder":"1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgVE2upms","required":true}],"warnings":[],"compliance_note":null,"template_required":false},{"id":"n5","type":"end_flow","label":"End","description":"Flow ends","missing_config":[],"warnings":[],"compliance_note":null,"template_required":false}],"required_integrations":[{"key":"google_sheets","name":"Google Sheets","reason":"To log customer ratings"}],"templates_needed":[{"suggested_name":"review_request","category":"MARKETING","purpose":"Collect customer reviews","body_preview":"Hi {{1}}, how was your experience with {{2}}? Please rate us! ⭐","approval_time":"24-48 hours"}],"compliance_flags":[],"missing_info":[],"blocking_issues":[],"overall_status":"needs_config","config_completion_percent":30}'),

(null, 'Abandoned Cart Recovery', 'Send WhatsApp reminders to customers who added items to cart but did not checkout', ARRAY['cart', 'ecommerce', 'recovery', 'abandoned', 'shopify'], true, '{"workflow_name":"Abandoned Cart Recovery","description":"Recover abandoned carts via WhatsApp","trigger_summary":"Webhook when cart is abandoned","nodes":[{"id":"n1","type":"trigger_webhook","label":"Cart abandoned webhook","description":"Shopify/WooCommerce cart abandoned event","missing_config":[{"field":"webhook_url","label":"Webhook URL","type":"url","placeholder":"https://your-server.com/webhook/cart","required":true}],"warnings":[],"compliance_note":null,"template_required":false},{"id":"n2","type":"wait_delay","label":"Wait 1 hour","description":"Wait before sending reminder","missing_config":[{"field":"delay_minutes","label":"Delay (minutes)","type":"number","placeholder":"60","required":true}],"warnings":[],"compliance_note":null,"template_required":false},{"id":"n3","type":"send_template","label":"Send cart reminder","description":"Send cart recovery message with items","missing_config":[{"field":"template_name","label":"Template name","type":"text","placeholder":"cart_recovery","required":true}],"warnings":[],"compliance_note":"Must use MARKETING category","template_required":true},{"id":"n4","type":"collect_input","label":"Wait for response","description":"Wait to see if customer completes purchase","missing_config":[],"warnings":[],"compliance_note":null,"template_required":false},{"id":"n5","type":"end_flow","label":"End","description":"Flow ends","missing_config":[],"warnings":[],"compliance_note":null,"template_required":false}],"required_integrations":[{"key":"shopify","name":"Shopify/WooCommerce","reason":"To receive cart abandonment webhooks"}],"templates_needed":[{"suggested_name":"cart_recovery","category":"MARKETING","purpose":"Recover abandoned carts","body_preview":"Hi {{1}}, you left items in your cart! Complete your purchase and get 10% off with code SAVE10. 🛒","approval_time":"24-48 hours"}],"compliance_flags":[],"missing_info":[],"blocking_issues":[],"overall_status":"needs_config","config_completion_percent":25}'),

(null, 'Appointment Reminder', 'Send appointment or meeting reminders via WhatsApp 24 hours before the scheduled time', ARRAY['appointment', 'reminder', 'calendar', 'booking', 'scheduling'], true, '{"workflow_name":"Appointment Reminder","description":"Remind customers about upcoming appointments","trigger_summary":"24 hours before appointment time","nodes":[{"id":"n1","type":"trigger_scheduled","label":"24h before appointment","description":"Triggered 24 hours before each appointment","missing_config":[{"field":"calendar_id","label":"Google Calendar ID","type":"text","placeholder":"primary","required":true}],"warnings":[],"compliance_note":null,"template_required":false},{"id":"n2","type":"send_template","label":"Send reminder","description":"Send appointment reminder with confirm/reschedule buttons","missing_config":[{"field":"template_name","label":"Template name","type":"text","placeholder":"appointment_reminder","required":true}],"warnings":[],"compliance_note":"Use UTILITY category for appointment reminders","template_required":true},{"id":"n3","type":"condition_button_click","label":"Response check","description":"Check if customer confirms or wants to reschedule","missing_config":[],"warnings":[],"compliance_note":null,"template_required":false},{"id":"n4","type":"end_flow","label":"End","description":"Flow ends","missing_config":[],"warnings":[],"compliance_note":null,"template_required":false}],"required_integrations":[{"key":"google_calendar","name":"Google Calendar","reason":"To fetch upcoming appointments"}],"templates_needed":[{"suggested_name":"appointment_reminder","category":"UTILITY","purpose":"Remind about appointments","body_preview":"Hi {{1}}, your appointment for {{2}} is tomorrow at {{3}}. Reply YES to confirm or NO to reschedule.","approval_time":"24-48 hours"}],"compliance_flags":[],"missing_info":[],"blocking_issues":[],"overall_status":"needs_config","config_completion_percent":35}')
on conflict do nothing;

-- Seed dummy contacts for testing
insert into public.contacts (user_id, name, phone, tags, status, attributes)
select auth.uid(), 'Rahul Sharma', '919876543210', ARRAY['lead', 'premium'], 'active', '{"source": "website", "city": "Mumbai"}'::jsonb
where exists (select 1 from auth.users limit 1)
on conflict do nothing;
